#!/bin/bash

sudo apt-get remove --purge webbrowser-app aisleriot gnome-mahjongg totem checkbox-gui gnome-font-viewer gnome-mines gnome-sudoku onboard xdiagnose example-content transmission-common transmission-gtk brltty whoopsie gnome-calendar -y
sudo apt-get autoremove -y && sudo apt-get clean all -y && sudo apt-get autoclean all -y
