#!/bin/bash

# My custom icons
# Geddit dark background && tab width && plugins && line numbers && highlighting
# Slovak language && Text entry -> alt+Lshift
# https://nastavenia.tuke.sk/posta/thunderbird-nastavenie
# Appearence/Behavior/Show the menus for a window/In the window's title bar
# http://askubuntu.com/questions/31786/chrome-asks-for-password-to-unlock-keyring-on-startup
# http://askubuntu.com/questions/761180/wifi-doesnt-work-after-suspend-after-16-04-upgrade
# http://askubuntu.com/questions/142128/open-windows-in-center-of-screen
# Mozilla setup
# GIMP Single window mode
# Atom setup

# Update and Upgrade
sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y autoremove

# Grub
sudo apt-get -y remove memtest86+
sudo update-grub

# Themes
sudo add-apt-repository -y ppa:docky-core/stable
sudo add-apt-repository -y ppa:noobslab/macbuntu
sudo apt-get update
sudo apt-get install -y docky macbuntu-os-ithemes-lts-v7

# My Applications (alacarte == Main Menu)
sudo add-apt-repository -y ppa:webupd8team/atom
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
sudo add-apt-repository -y ppa:eugenesan/ppa
sudo apt-get update
sudo apt-get install -y atom indicator-netspeed ubuntu-make unity-tweak-tool gnome-tweak-tool chromium-browser nautilus-dropbox alacarte shutter gimp vlc ubuntu-mate-welcome compizconfig-settings-manager deluge shutter inkscape calibre htop xclip exfat-utils exfat-fuse tlp tlp-rdw smartgit

# Android Studio via umake (Android Studio -> Tools -> Create desktop Entry)
umake android

a

# Spotify
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update
sudo apt-get install -y spotify-client

# School
sudo apt-get install -y gcc make valgrind gdb cgdb gedit git libncurses5-dev libncurses5 cppcheck ncurses-doc vim nano mcedit synaptic arduino fritzing virtualbox

# Remove bloat
sudo apt-get remove --purge -y aisleriot gnome-mahjongg imagemagick totem checkbox-gui gnome-font-viewer gnome-mines gnome-sudoku onboard example-content transmission-common transmission-gtk brltty gnome-calendar

sudo apt-get -y autoremove && sudo apt-get -y clean all && sudo apt-get -y autoclean all

sudo rm -rf /usr/share/applications/webbrowser-app.desktop
sudo rm -rf /usr/share/applications/ubuntu-amazon-default.desktop
sudo rm -rf /usr/share/applications/gnome-system-log.desktop
